### ISSUE TITLE
Safe renaming at destination if file exists

### ISSUE THREAD

**Issue by mrmadcow** [bernmic/ocrmypdf-watchdog#1]
On the final rename to destination folder, existing files will be overwritten without warning. A safer behavior would be to append a suffix to the new file in that case to avoid loss of data.

**Comment by skl283** [comment]
Could you please push these Changes to hub.docker.com? Last Update on hub.docker.com is a year ago and this fix is merged on jan 2020.

thank you!

**Comment by bernmic** [comment]
Done
