### ISSUE TITLE
Not working in a Raspberry Docker ?

### ISSUE THREAD

**Issue by Alwiz79** [bernmic/ocrmypdf-watchdog#7]
I try to run this in my Docker on the Raspberry Pi 4.
I used the yml file provided in this project and uncommented the line with the image.

The container says it's running, but in the logs I can see
`standard_init_linux.go:228: exec user process caused: exec format error`

Also filles in the input are not processed.
Has anyone an idea what the problem could be?

**Comment by jxsl13** [comment]
arm vs amd64 architecture mismatch. build the project on your raspberry pi yourself.

**Comment by Alwiz79** [comment]
sad to hear that...I don't know how to do that

**Comment by bernmic** [comment]
The base image is available for arm64. So I can try to provide an image for RaspberryOS 64bit. Do you run this version?

Update: there is now an arm64 image on Docker hub. So, if you use the 64Bit RaspiOS this should work.

**Comment by Alwiz79** [comment]
@bernmic: thank you, I'll give it a try

**Comment by Alwiz79** [comment]
Works great! Thank you very much
